version: "3.9"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: sampledb
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tomcat-net

  tomcat:
    build:
      context: .
      dockerfile: tomcat/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - ./app/sample:/usr/local/tomcat/webapps/sample   # HOT DEPLOY 🚀
      - tomcat-logs:/usr/local/tomcat/logs
    networks:
      - tomcat-net

volumes:
  tomcat-logs:

networks:
  tomcat-net:
